repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      types: [file]  # override `types: [python]`
      files: (\.py$|^SConstruct$|/SConscript$)
      exclude: (^tests/_lib_vendors|^(tests|examples)/lib)  # Ignore 3rd party stuff
      args:
          - "--line-length=100"
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: mixed-line-ending
      exclude: (^tests/_lib_vendors|^(tests|examples)/lib)  # Ignore 3rd party stuff
    - id: trailing-whitespace
      exclude: (^tests/_lib_vendors|^(tests|examples)/lib)  # Ignore 3rd party stuff
-   repo: local
    hooks:
    - id: git_actions_pin
      name: "Gitub actions pin 3rd party repos"
      entry: python ./misc/pin_github_actions.py check
      language: python
      language_version: python3
      files: ^.github/
